/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.event.KeyEvent;

import javax.swing.JFrame;
import javax.swing.UIManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Window.Type;

@SuppressWarnings("unused")
public class AdvanceCalculator extends javax.swing.JFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	double firstnum,secondnum,thirdnum,result;
    String operations;
    private Object math;
    /**
     * Creates new form AdvanceCalculator
     */
    public AdvanceCalculator() {
    	setType(Type.POPUP);
    	setBackground(new Color(255, 255, 255));
    	setForeground(new Color(0, 0, 0));
    	setFont(new Font("Segoe UI Symbol", Font.BOLD, 12));
    	getContentPane().setBackground(new Color(0, 0, 51));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	setTitle("Advance Calculator");
        jtxtdisplay = new javax.swing.JTextField();
        jbtn7 = new javax.swing.JButton();
        jbtn7.setBackground(new Color(240, 255, 255));
        jbtndiv = new javax.swing.JButton();
        jbtndiv.setForeground(new Color(0, 0, 0));
        jbtndiv.setBackground(new Color(143, 188, 143));
        jbtn8 = new javax.swing.JButton();
        jbtn8.setBackground(new Color(240, 255, 255));
        jbtn9 = new javax.swing.JButton();
        jbtn9.setBackground(new Color(240, 255, 255));
        jbtn4 = new javax.swing.JButton();
        jbtn4.setBackground(new Color(240, 255, 255));
        jbtn5 = new javax.swing.JButton();
        jbtn5.setBackground(new Color(240, 255, 255));
        jbtn6 = new javax.swing.JButton();
        jbtn6.setBackground(new Color(240, 255, 255));
        jbtnmul = new javax.swing.JButton();
        jbtnmul.setForeground(new Color(0, 0, 0));
        jbtnmul.setBackground(new Color(143, 188, 143));
        jbtn0 = new javax.swing.JButton();
        jbtn0.setBackground(new Color(240, 255, 255));
        jbtndot = new javax.swing.JButton();
        jbtndot.setForeground(new Color(0, 0, 0));
        jbtndot.setBackground(new Color(240, 255, 255));
        jbtnequal = new javax.swing.JButton();
        jbtnequal.setBackground(new Color(240, 255, 255));
        jbtn1 = new javax.swing.JButton();
        jbtn1.setBackground(new Color(240, 255, 255));
        jbtn2 = new javax.swing.JButton();
        jbtn2.setBackground(new Color(240, 255, 255));
        jbtnclear = new javax.swing.JButton();
        jbtnclear.setForeground(new Color(255, 255, 255));
        jbtnclear.setBackground(new Color(178, 34, 34));
        jbtndel = new javax.swing.JButton();
        jbtndel.setForeground(new Color(255, 255, 255));
        jbtndel.setBackground(new Color(218, 165, 32));
        jbtn3 = new javax.swing.JButton();
        jbtn3.setBackground(new Color(240, 255, 255));
        jbtnminus = new javax.swing.JButton();
        jbtnminus.setForeground(new Color(0, 0, 0));
        jbtnminus.setBackground(new Color(143, 188, 143));
        jbtnadd = new javax.swing.JButton();
        jbtnadd.setForeground(new Color(0, 0, 0));
        jbtnadd.setBackground(new Color(143, 188, 143));
        jbtnplus = new javax.swing.JButton();
        jbtnplus.setForeground(new Color(0, 0, 0));
        jbtnplus.setBackground(new Color(240, 255, 255));
        jbtnpow = new javax.swing.JButton();
        jbtnpow.setForeground(new Color(255, 255, 255));
        jbtnpow.setBackground(new Color(0, 0, 0));
        jbtnsqr = new javax.swing.JButton();
        jbtnsqr.setForeground(new Color(255, 255, 255));
        jbtnsqr.setBackground(new Color(0, 0, 0));
        jbtncube = new javax.swing.JButton();
        jbtncube.setForeground(new Color(255, 255, 255));
        jbtncube.setBackground(new Color(0, 0, 0));
        jbtnsqrt = new javax.swing.JButton();
        jbtnsqrt.setForeground(new Color(255, 255, 255));
        jbtnsqrt.setBackground(new Color(0, 0, 0));
        jbtnyroot = new javax.swing.JButton();
        jbtnyroot.setForeground(new Color(255, 255, 255));
        jbtnyroot.setBackground(new Color(0, 0, 0));
        jbtnover = new javax.swing.JButton();
        jbtnover.setForeground(new Color(255, 255, 255));
        jbtnover.setBackground(new Color(0, 0, 0));
        jbtnpi = new javax.swing.JButton();
        jbtnpi.setForeground(new Color(255, 255, 255));
        jbtnpi.setBackground(new Color(0, 0, 0));
        jbtnfact = new javax.swing.JButton();
        jbtnfact.setForeground(new Color(255, 255, 255));
        jbtnfact.setBackground(new Color(0, 0, 0));
        jbtnlog = new javax.swing.JButton();
        jbtnlog.setForeground(new Color(255, 255, 255));
        jbtnlog.setBackground(new Color(0, 0, 0));
        jbtncuberoot = new javax.swing.JButton();
        jbtncuberoot.setForeground(new Color(255, 255, 255));
        jbtncuberoot.setBackground(new Color(0, 0, 0));
        jbtnflr = new javax.swing.JButton();
        jbtnflr.setForeground(new Color(255, 255, 255));
        jbtnflr.setBackground(new Color(0, 0, 0));
        jbtnceil = new javax.swing.JButton();
        jbtnceil.setForeground(new Color(255, 255, 255));
        jbtnceil.setBackground(new Color(0, 0, 0));
        jbtnabs = new javax.swing.JButton();
        jbtnabs.setForeground(new Color(255, 255, 255));
        jbtnabs.setBackground(new Color(0, 0, 0));
        jbtnmod = new javax.swing.JButton();
        jbtnmod.setForeground(new Color(255, 255, 255));
        jbtnmod.setBackground(new Color(0, 0, 0));
        jbtnsum = new javax.swing.JButton();
        jbtnsum.setForeground(new Color(255, 255, 255));
        jbtnsum.setBackground(new Color(0, 0, 0));
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuBar1.setBackground(new Color(248, 248, 255));
        jMenu1 = new javax.swing.JMenu();
        jMenu1.setBackground(new Color(240, 248, 255));
        jMenu1.setFont(new Font("Nirmala UI", Font.BOLD, 11));
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem1.setFont(new Font("Microsoft New Tai Lue", Font.PLAIN, 12));
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem2.setFont(new Font("Microsoft New Tai Lue", Font.PLAIN, 12));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusableWindowState(false);
        setPreferredSize(new Dimension(502, 374));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jtxtdisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxtdisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtdisplay.setText("0");
        jtxtdisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtdisplayActionPerformed(evt);
            }
        });
        jtxtdisplay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtdisplayKeyTyped(evt);
            }
        });

        jbtn7.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn7.setText("7");
        jbtn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn7ActionPerformed(evt);
            }
        });
        jbtn7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtn7KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbtn7KeyTyped(evt);
            }
        });

        jbtndiv.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtndiv.setText("/");
        jbtndiv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtndiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndivActionPerformed(evt);
            }
        });

        jbtn8.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn8.setText("8");
        jbtn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn8ActionPerformed(evt);
            }
        });

        jbtn9.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn9.setText("9");
        jbtn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn9ActionPerformed(evt);
            }
        });

        jbtn4.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn4.setText("4");
        jbtn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn4ActionPerformed(evt);
            }
        });

        jbtn5.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn5.setText("5");
        jbtn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn5ActionPerformed(evt);
            }
        });

        jbtn6.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn6.setText("6");
        jbtn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn6ActionPerformed(evt);
            }
        });

        jbtnmul.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnmul.setText("*");
        jbtnmul.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmulActionPerformed(evt);
            }
        });

        jbtn0.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn0.setText("0");
        jbtn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn0ActionPerformed(evt);
            }
        });

        jbtndot.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtndot.setText(".");
        jbtndot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtndot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndotActionPerformed(evt);
            }
        });

        jbtnequal.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnequal.setText("=");
        jbtnequal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnequalActionPerformed(evt);
            }
        });

        jbtn1.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn1.setText("1");
        jbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn1ActionPerformed(evt);
            }
        });

        jbtn2.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn2.setText("2");
        jbtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn2ActionPerformed(evt);
            }
        });

        jbtnclear.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
        jbtnclear.setText("CLEAR");
        jbtnclear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnclearActionPerformed(evt);
            }
        });

        jbtndel.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
        jbtndel.setText("DELETE");
        jbtndel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndelActionPerformed(evt);
            }
        });

        jbtn3.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtn3.setText("3");
        jbtn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn3ActionPerformed(evt);
            }
        });

        jbtnminus.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnminus.setText("-");
        jbtnminus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnminusActionPerformed(evt);
            }
        });

        jbtnadd.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnadd.setText("+");
        jbtnadd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnaddActionPerformed(evt);
            }
        });

        jbtnplus.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnplus.setText("\u00B1");
        jbtnplus.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnplusActionPerformed(evt);
            }
        });

        jbtnpow.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnpow.setText("x^y");
        jbtnpow.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnpow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpowActionPerformed(evt);
            }
        });

        jbtnsqr.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnsqr.setText("x^2");
        jbtnsqr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrActionPerformed(evt);
            }
        });

        jbtncube.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtncube.setText("x^3");
        jbtncube.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtncube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncubeActionPerformed(evt);
            }
        });

        jbtnsqrt.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnsqrt.setText("\u221A");
        jbtnsqrt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsqrtActionPerformed(evt);
            }
        });

        jbtnyroot.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnyroot.setText("y\u221Ax");
        jbtnyroot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnyroot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnyrootActionPerformed(evt);
            }
        });

        jbtnover.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnover.setText("1/X");
        jbtnover.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnoverActionPerformed(evt);
            }
        });

        jbtnpi.setFont(new Font("Calibri", Font.BOLD, 14)); // NOI18N
        jbtnpi.setText("\u03C0");
        jbtnpi.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnpi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpiActionPerformed(evt);
            }
        });

        jbtnfact.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnfact.setText("X!");
        jbtnfact.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnfact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnfactActionPerformed(evt);
            }
        });

        jbtnlog.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnlog.setText("log");
        jbtnlog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnlog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnlogActionPerformed(evt);
            }
        });

        jbtncuberoot.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtncuberoot.setText("3\u221Ax");
        jbtncuberoot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtncuberoot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtncuberootActionPerformed(evt);
            }
        });

        jbtnflr.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnflr.setText("Flr");
        jbtnflr.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnflr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnflrActionPerformed(evt);
            }
        });

        jbtnceil.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnceil.setText("Ceil");
        jbtnceil.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnceil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnceilActionPerformed(evt);
            }
        });

        jbtnabs.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnabs.setText("Abs");
        jbtnabs.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnabs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnabsActionPerformed(evt);
            }
        });

        jbtnmod.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnmod.setText("%");
        jbtnmod.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnmod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmodActionPerformed(evt);
            }
        });

        jbtnsum.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jbtnsum.setText("\u03A3");
        jbtnsum.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtnsum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnsumActionPerformed(evt);
            }
        });

        jMenu1.setText("MODE");

        jMenuItem1.setText("Standard");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Scientific");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(490, 490, 490))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jbtnequal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnsum, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtncube, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtncuberoot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtnpow, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbtnyroot, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnceil, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnabs, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnover, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnflr, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(140, 140, 140))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jtxtdisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnclear, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndiv, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmul, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnminus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnflr, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jbtnsqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jbtnsqr, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnceil, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtncuberoot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtncube, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jbtnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jbtnabs, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnyroot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnpow, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnpi, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnmod, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnover, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnfact, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnlog, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnsum, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn0, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtndot, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbtnplus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtnequal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 338, 412);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.setResizable(false);
        this.setSize(331, 420);
        jbtnpow.setVisible(false);
        jbtncuberoot.setVisible(false);
        jbtnflr.setVisible(false);
        jbtnsqr.setVisible(false);
        jbtnlog.setVisible(false);
        jbtnceil.setVisible(false);
        jbtncube.setVisible(false);
        jbtnfact.setVisible(false);
        jbtnabs.setVisible(false);
        jbtnsqrt.setVisible(false);
        jbtnpi.setVisible(false);
        jbtnmod.setVisible(false);
        jbtnyroot.setVisible(false);
        jbtnover.setVisible(false);
        jbtnsum.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn7ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn7.getText();
        else
            num = jtxtdisplay.getText() + jbtn7.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn7ActionPerformed

    private void jbtndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndivActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("/");
    }//GEN-LAST:event_jbtndivActionPerformed

    private void jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn8ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn8.getText();
        else
            num = jtxtdisplay.getText() + jbtn8.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn8ActionPerformed

    private void jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn9ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn9.getText();
        else
            num = jtxtdisplay.getText() + jbtn9.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn9ActionPerformed

    private void jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn4ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn4.getText();
        else
            num = jtxtdisplay.getText() + jbtn4.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn4ActionPerformed

    private void jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn5ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn5.getText();
        else
            num = jtxtdisplay.getText() + jbtn5.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn5ActionPerformed

    private void jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn6ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn6.getText();
        else
            num = jtxtdisplay.getText() + jbtn6.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn6ActionPerformed

    private void jbtnmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmulActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("*");
    }//GEN-LAST:event_jbtnmulActionPerformed

    private void jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn0ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn0.getText();
        else
            num = jtxtdisplay.getText() + jbtn0.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn0ActionPerformed

    private void jbtndotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndotActionPerformed
        String num = jtxtdisplay.getText();
        if(!jtxtdisplay.getText().contains(".")){
            num = jtxtdisplay.getText() + jbtndot.getText();  
        }                          
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtndotActionPerformed

    private void jbtnequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnequalActionPerformed
        String ans;
        secondnum = Double.parseDouble(jtxtdisplay.getText());
        if(result != 0)
            firstnum = result;
        if(operations == "+"){
            result = firstnum + secondnum;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "-"){
            result = firstnum - secondnum;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "*"){
            result = firstnum * secondnum;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "/"){
            result = firstnum / secondnum;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "%"){
            result = firstnum % secondnum;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "x^y"){
            result = Math.pow(firstnum, secondnum);
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "yroot"){
            result = Math.pow(firstnum, 1.0/secondnum);
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
        else if(operations == "summation"){
            for(double i = firstnum; i <= secondnum;i++)
                result += i;
            ans = String.format("%.2f", result);
            jtxtdisplay.setText(ans);
        }
    }//GEN-LAST:event_jbtnequalActionPerformed

    private void jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn1ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn1.getText();
        else
            num = jtxtdisplay.getText() + jbtn1.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn1ActionPerformed

    private void jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn2ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn2.getText();
        else
            num = jtxtdisplay.getText() + jbtn2.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn2ActionPerformed

    private void jbtndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndelActionPerformed
        String num = "";
        if(jtxtdisplay.getText().length() != 0){
            StringBuilder strB = new StringBuilder(jtxtdisplay.getText());
            strB.deleteCharAt(jtxtdisplay.getText().length() - 1);
            num = strB.toString();
            jtxtdisplay.setText(num);
            if(jtxtdisplay.getText().length() == 0)
                jtxtdisplay.setText("0");
        }
        else{
            jtxtdisplay.setText("0");
        }
    }//GEN-LAST:event_jbtndelActionPerformed

    private void jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn3ActionPerformed
        String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn3.getText();
        else
            num = jtxtdisplay.getText() + jbtn3.getText();        
        jtxtdisplay.setText(num);
    }//GEN-LAST:event_jbtn3ActionPerformed

    private void jbtnminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnminusActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("-");
    }//GEN-LAST:event_jbtnminusActionPerformed

    private void jbtnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnaddActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("+");
    }//GEN-LAST:event_jbtnaddActionPerformed

    private void jbtnclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnclearActionPerformed
        jtxtdisplay.setText("0");
        result = 0;
        firstnum = 0;
    }//GEN-LAST:event_jbtnclearActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        this.setResizable(false);
        this.setSize(300, 420);
        jbtnpow.setVisible(false);
        jbtncuberoot.setVisible(false);
        jbtnflr.setVisible(false);
        jbtnsqr.setVisible(false);
        jbtnlog.setVisible(false);
        jbtnceil.setVisible(false);
        jbtncube.setVisible(false);
        jbtnfact.setVisible(false);
        jbtnabs.setVisible(false);
        jbtnsqrt.setVisible(false);
        jbtnpi.setVisible(false);
        jbtnmod.setVisible(false);
        jbtnyroot.setVisible(false);
        jbtnover.setVisible(false);
        jbtnsum.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        this.setResizable(false);
        this.setSize(580, 420);
        jtxtdisplay.setSize(550, 30);
        jbtnpow.setVisible(true);
        jbtncuberoot.setVisible(true);
        jbtnflr.setVisible(true);
        jbtnsqr.setVisible(true);
        jbtnlog.setVisible(true);
        jbtnceil.setVisible(true);
        jbtncube.setVisible(true);
        jbtnfact.setVisible(true);
        jbtnabs.setVisible(true);
        jbtnsqrt.setVisible(true);
        jbtnpi.setVisible(true);
        jbtnmod.setVisible(true);
        jbtnyroot.setVisible(true);
        jbtnover.setVisible(true);
        jbtnsum.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jbtnplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnplusActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num *= -1;
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnplusActionPerformed

    private void jbtnpowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpowActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("x^y");
    }//GEN-LAST:event_jbtnpowActionPerformed

    private void jbtnsqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.pow(num, 2);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnsqrActionPerformed

    private void jbtncubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncubeActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.pow(num, 3);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtncubeActionPerformed

    private void jbtnsqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsqrtActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.sqrt(num);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnsqrtActionPerformed

    private void jbtnyrootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnyrootActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("yroot");
    }//GEN-LAST:event_jbtnyrootActionPerformed

    private void jbtnoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnoverActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = 1/num;
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnoverActionPerformed

    private void jbtnpiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpiActionPerformed
        double pi =  3.1415926535897932384626433832795;
        String ans = String.format("%.6f", pi);
        jtxtdisplay.setText(ans);
    }//GEN-LAST:event_jbtnpiActionPerformed

    private void jbtnfactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnfactActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        double ans = 1;
        for(double i = num;i > 0; i--)
        ans *= i;
        jtxtdisplay.setText(String.valueOf(ans));
    }//GEN-LAST:event_jbtnfactActionPerformed

    private void jbtnlogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnlogActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.log(num);
        jtxtdisplay.setText(String.valueOf(num));// TODO add your handling code here:
    }//GEN-LAST:event_jbtnlogActionPerformed

    private void jbtnflrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnflrActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.floor(num);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnflrActionPerformed

    private void jbtnceilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnceilActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.ceil(num);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnceilActionPerformed

    private void jbtnabsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnabsActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.abs(num);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtnabsActionPerformed

    private void jbtnmodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmodActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("%");
    }//GEN-LAST:event_jbtnmodActionPerformed

    private void jbtnsumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnsumActionPerformed
        firstnum = Double.parseDouble(jtxtdisplay.getText());
        jtxtdisplay.setText("0");
        operations = ("summation");
    }//GEN-LAST:event_jbtnsumActionPerformed

    private void jbtncuberootActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtncuberootActionPerformed
        double num = Double.parseDouble(String.valueOf(jtxtdisplay.getText()));
        num = Math.cbrt(num);
        jtxtdisplay.setText(String.valueOf(num));
    }//GEN-LAST:event_jbtncuberootActionPerformed

    private void jtxtdisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtdisplayActionPerformed
        this.setResizable(true);
        this.setSize(568, 40);
        jtxtdisplay.setSize(568, 40);
    }//GEN-LAST:event_jtxtdisplayActionPerformed

    private void jtxtdisplayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtdisplayKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_jtxtdisplayKeyTyped

    private void jbtn7KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn7KeyPressed
        
    }//GEN-LAST:event_jbtn7KeyPressed

    private void jbtn7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn7KeyTyped
        char c = evt.getKeyChar();
        if(c == KeyEvent.VK_7){
            String num = jtxtdisplay.getText();
        if(num.equals("0"))
            num = jbtn7.getText();
        else
            num = jtxtdisplay.getText() + jbtn7.getText();        
        jtxtdisplay.setText(num);
        }
    }//GEN-LAST:event_jbtn7KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdvanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdvanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdvanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdvanceCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdvanceCalculator().setVisible(true);
            }
        });
    }

    public Object getMath() {
		return math;
	}

	public void setMath(Object math) {
		this.math = math;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JButton jbtn0;
    private javax.swing.JButton jbtn1;
    private javax.swing.JButton jbtn2;
    private javax.swing.JButton jbtn3;
    private javax.swing.JButton jbtn4;
    private javax.swing.JButton jbtn5;
    private javax.swing.JButton jbtn6;
    private javax.swing.JButton jbtn7;
    private javax.swing.JButton jbtn8;
    private javax.swing.JButton jbtn9;
    private javax.swing.JButton jbtnabs;
    private javax.swing.JButton jbtnadd;
    private javax.swing.JButton jbtnceil;
    private javax.swing.JButton jbtnclear;
    private javax.swing.JButton jbtncube;
    private javax.swing.JButton jbtncuberoot;
    private javax.swing.JButton jbtndel;
    private javax.swing.JButton jbtndiv;
    private javax.swing.JButton jbtndot;
    private javax.swing.JButton jbtnequal;
    private javax.swing.JButton jbtnfact;
    private javax.swing.JButton jbtnflr;
    private javax.swing.JButton jbtnlog;
    private javax.swing.JButton jbtnminus;
    private javax.swing.JButton jbtnmod;
    private javax.swing.JButton jbtnmul;
    private javax.swing.JButton jbtnover;
    private javax.swing.JButton jbtnpi;
    private javax.swing.JButton jbtnplus;
    private javax.swing.JButton jbtnpow;
    private javax.swing.JButton jbtnsqr;
    private javax.swing.JButton jbtnsqrt;
    private javax.swing.JButton jbtnsum;
    private javax.swing.JButton jbtnyroot;
    private javax.swing.JTextField jtxtdisplay;
}